services:

  listener:
    build: .
    networks:
      listener_net: {}
    command: ros2 run demo_nodes_cpp listener

  dds-router-listener:
    image: husarnet/dds-router
    depends_on:
      - dds-router-talker
    networks:
      listener_net: {}
      inter_net:
        ipv4_address: 172.77.0.11
    volumes:
      - ./router-config.listener.yaml:/config.yaml
    command: ddsrouter -c /config.yaml -r 10

  talker:
    build: .
    networks:
      talker_net: {}
    command: ros2 run demo_nodes_cpp talker

  dds-router-talker:
    image: husarnet/dds-router
    networks:
      talker_net: {}
      inter_net:
        ipv4_address: 172.77.0.22
    volumes:
      - ./router-config.talker.yaml:/config.yaml
    command: ddsrouter -c /config.yaml -r 10

networks:
  listener_net:
  talker_net:
  inter_net:
    ipam:
      driver: default
      config:
      - subnet: 172.77.0.0/24
        gateway: 172.77.0.1
  default:
    driver: none