allowlist:
  - name: "rt/chatter"
    type: "std_msgs::msg::dds_::String_"

internal_partipant:
  type: local
  domain: 0

external_partipant:
  type: local-discovery-server
  id: 201
  
  connection-addresses:
    - id: 200
      addresses:
        - ip: "172.77.0.22"
          port: 11811

      
