allowlist:
  - name: "rt/chatter"
    type: "std_msgs::msg::dds_::String_"

internal_partipant:
  type: local
  domain: 0

external_partipant:
  type: local-discovery-server
  id: 202

  connection-addresses:
    - id: 200
      addresses:
        - domain: talker # Husarnet hostname
          port: 11811
          transport: "udp"


      
