version: v2.0

builtin:
  - name: "rt/chatter"
    type: "std_msgs::msg::dds_::String_"

allowlist:
  - name: "rt/chatter"
    type: "std_msgs::msg::dds_::String_"

participants:

  - name: SimpleParticipant
    kind: local
    domain: 0

  - name: ClientWAN
    kind: local-discovery-server
    discovery-server-guid:
      id: 202
    connection-addresses:
      - discovery-server-guid:
          id: 200
        addresses:
          - domain: talker  # Husarnet hostname
            port: 11811
            transport: udp
